packageImportMethod: copy
allowBuilds:
  '@scarf/scarf': false
  unrs-resolver: false
ignoredOptionalDependencies:
  - '@fastify/static'
overrides:
  adm-zip: 0.6.0
  find-my-way: 9.7.0
  js-yaml: 5.2.3
