import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { Test } from '@nestjs/testing';
import { FastifyAdapter, type NestFastifyApplication } from '@nestjs/platform-fastify';
import { AppModule } from '../../src/app.module';
import { ConfigService } from '../../src/config/config.service';
import { DatabaseService } from '../../src/database/database.service';
import { AccountActivityService } from '../../src/database/account-activity.service';
import { ScyllaService } from '../../src/scylla/scylla.service';
import { RedisService } from '../../src/redis/redis.service';
import { ObjectStorageService } from '../../src/storage/object-storage.service';

jest.mock('dotenv', () => ({ config: jest.fn() }));

describe('Documented HTTP route inventory', () => {
  it('matches every application route registered by the real Nest module graph', async () => {
    const previousEnvironment = process.env;
    let app: NestFastifyApplication | undefined;
    try {
      // No developer .env, connection, worker, or network listener is used here.
      process.env = {
        ENV: 'test', JWT_SECRET: 'j'.repeat(32), PHONE_ENCRYPTION_KEY: 'e'.repeat(32), PHONE_HASH_KEY: 'h'.repeat(32),
        POSTGRES_HOST: 'localhost', POSTGRES_USER: 'fixture', POSTGRES_PASSWORD: 'fixture', POSTGRES_DB: 'histae-test',
        RATE_LIMIT_STORE: 'memory', MAINTENANCE_MODE: 'disabled', SCYLLA_ENABLED: 'false',
        SMS_PROVIDER: 'disabled', BILLING_PROVIDER: 'disabled', PUSH_PROVIDER: 'disabled', PHOTO_MODERATION_PROVIDER: 'disabled',
      };
      const builder = Test.createTestingModule({ imports: [AppModule] })
        .overrideProvider(ConfigService).useValue(new ConfigService());
      for (const provider of [DatabaseService, AccountActivityService, ScyllaService, RedisService, ObjectStorageService]) {
        builder.overrideProvider(provider).useValue({ enabled: false });
      }
      const module = await builder.compile();
      // HEAD aliases are generated by Fastify, not part of the application inventory.
      // Explicit @Head routes would still register and must be documented.
      const adapter = new FastifyAdapter({ exposeHeadRoutes: false, logger: false });
      const registered: string[] = [];
      adapter.getInstance().addHook('onRoute', route => {
        for (const method of Array.isArray(route.method) ? route.method : [route.method]) {
          registered.push(`${method} ${route.url}`);
        }
      });
      app = module.createNestApplication<NestFastifyApplication>(adapter, { logger: false });
      await app.init();
      await adapter.getInstance().ready();
      const documented = documentationRoutes(await readFile(resolve(__dirname, '../../routes.md'), 'utf8'));
      expect(registered.length).toBeGreaterThan(0);
      expect(routeDifference(documented, registered)).toEqual({ undocumented: [], obsolete: [] });
    } finally {
      try { await app?.close(); } finally { process.env = previousEnvironment; }
    }
  });

  it('rejects a duplicate documented method and path', () => {
    expect(() => documentationRoutes('| GET | `/api/example` | A |\n| GET | `/api/example` | B |'))
      .toThrow('Duplicate documented route: GET /api/example');
  });

  it('rejects a malformed inventory row instead of silently ignoring it', () => {
    expect(() => documentationRoutes('| POST | api/example | Missing backticks and slash |'))
      .toThrow('Invalid route inventory row');
  });

  it.each([
    { documented: [], registered: ['POST /api/example'], expected: { undocumented: ['POST /api/example'], obsolete: [] } },
    { documented: ['GET /api/example'], registered: [], expected: { undocumented: [], obsolete: ['GET /api/example'] } },
  ])('detects documentation drift: $expected', ({ documented, registered, expected }) => {
    expect(routeDifference(documented, registered)).toEqual(expected);
  });
});

function documentationRoutes(markdown: string): string[] {
  const routes = new Set<string>();
  let inCodeBlock = false;
  for (const line of markdown.split(/\r?\n/)) {
    if (/^\s*```/.test(line)) { inCodeBlock = !inCodeBlock; continue; }
    if (inCodeBlock || !/^\|\s*(?:GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|ALL)\b/.test(line)) continue;
    const match = /^\|\s*(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS|ALL)\s*\|\s*`(\/[^`\s]*)`\s*\|/.exec(line);
    if (!match) throw new Error(`Invalid route inventory row: ${line}`);
    const route = `${match[1]} ${match[2]}`;
    if (routes.has(route)) throw new Error(`Duplicate documented route: ${route}`);
    routes.add(route);
  }
  return [...routes].sort();
}

function routeDifference(documented: string[], registered: string[]) {
  const docs = new Set(documented), actual = new Set(registered);
  return {
    undocumented: [...actual].filter(route => !docs.has(route)).sort(),
    obsolete: [...docs].filter(route => !actual.has(route)).sort(),
  };
}
